### ISSUE TITLE
Help Needed Compiling devotedmc plugins

### ISSUE THREAD

**Issue by pvprangergod** [DevotedMC/Finale#6]
Hi im having trouble compiling plugins from these github pages
I use maven in my cmd after downloading the files
mvn install
I get these errors and struggled attempting to fix it

Downloading: http://repo.dmulloy2.net/content/groups/public/com/comphenix/protocol/ProtocolLib/4.0.0-SNAPSHOT/ProtocolLib-4.0.0-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 08:17 min
[INFO] Finished at: 2017-07-08T19:30:39+12:00
[INFO] Final Memory: 10M/188M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project Finale: Could not resolve dependencies for project com.github.maxopoly:Finale:jar:1.0.6: The following artifacts could not be resolved: org.spigotmc:spigot:jar:1.10-R0.1-SNAPSHOT, com.comphenix.protocol:ProtocolLib:jar:4.0.0-SNAPSHOT: Could not find artifact org.spigotmc:spigot:jar:1.10-R0.1-SNAPSHOT in spigot-repo (https://hub.spigotmc.org/nexus/content/repositories/snapshots/) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by ProgrammerDan** [comment]
Hi friend.

For your first step, go to spigotmc.com -- download BuildTools.jar -- and follow the instructions on Spigotmc.com to build Spigot locally. 

This is necessary before any plugin builds can be done :).

You'll need to build 1.10 -- so do `java -jar BuildTools.jar --rev 1.10` if my recollection serves.

Try that first, if you still can't build, ping this thread again.

**Comment by pvprangergod** [comment]
Hi i have spigot and buildtools already and have compiled other plugins such as mcmmo
I believe im having trouble with these plugins because this link
http://repo.dmulloy2.net/content/groups/public/com/comphenix/protocol/ProtocolLib/4.0.0-SNAPSHOT/ProtocolLib-4.0.0-SNAPSHOT.jar
Is being used as a dependency but it is a dead link

**Comment by pvprangergod** [comment]
Hi I reverted to 1.10 and get the same error, it seems the protocollib dependency is a dead link?

**Comment by ProgrammerDan** [comment]
Are you trying to compile for 1.12? If you are, use the mc1.12 branch, which doesn't need ProtocolLib.

**Comment by pvprangergod** [comment]
ive tried the 1.12 version with a new 1.12 spigot and i get similar errors

Downloading: https://repo.maven.apache.org/maven2/vg/civcraft/mc/civmodcore/CivModCore/1.6.0/CivModCore-1.6.0.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:27 min
[INFO] Finished at: 2017-07-09T15:49:41+12:00
[INFO] Final Memory: 9M/187M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project Finale: Could not resolve dependencies for project com.github.maxopoly:Finale:jar:1.1.0: The following artifacts could not be resolved: vg.civcraft.mc.civmodcore:CivModCore:jar:1.6.0, net.minelink:CombatTagPlus:jar:1.3.1-SNAPSHOT: Could not find artifact vg.civcraft.mc.civmodcore:CivModCore:jar:1.6.0 in spigot-repo (https://hub.spigotmc.org/nexus/content/repositories/snapshots/) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by ProgrammerDan** [comment]
Just uploading a build for CivModCore 1.6.0 now. Check over there for that -- you can install it using maven's "install:install-file" directive.

**Comment by pvprangergod** [comment]
ok i have installed civmodcore 1.6.0 but how do i make it a dependency to fix the error?
